### ISSUE TITLE
Cannot find topic for pose?

### ISSUE THREAD

**Issue by wajeehulhassanvii** [eborghi10/AR.Drone-ROS#2]
Hi! I am running this but cannot find the topic for pose, can you please help me with this? 

```
:~/ardrone_simulator$ rostopic list
/altimeter
/ardrone/bottom/camera_info
/ardrone/bottom/image_raw
/ardrone/bottom/image_raw/compressed
/ardrone/bottom/image_raw/compressed/parameter_descriptions
/ardrone/bottom/image_raw/compressed/parameter_updates
/ardrone/bottom/parameter_descriptions
/ardrone/bottom/parameter_updates
/ardrone/camera_info
/ardrone/front/camera_info
/ardrone/front/image_raw
/ardrone/front/image_raw/compressed
/ardrone/front/image_raw/compressed/parameter_descriptions
/ardrone/front/image_raw/compressed/parameter_updates
/ardrone/front/parameter_descriptions
/ardrone/front/parameter_updates
/ardrone/image_raw
/ardrone/image_raw/compressed
/ardrone/image_raw/compressed/parameter_descriptions
/ardrone/image_raw/compressed/parameter_updates
/ardrone/imu
/ardrone/land
/ardrone/navdata
/ardrone/navdata_raw_measures
/ardrone/reset
/ardrone/takeoff
/clock
/cmd_vel
/fix
/fix_velocity
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/gazebo_gui/parameter_descriptions
/gazebo_gui/parameter_updates
/ground_truth/state
/joint_states
/magnetic
/pressure_height
/rosout
/rosout_agg
/sonar_height
/tf
/tf_static
```

**Comment by eborghi10** [comment]
See [this presentation on page 37](http://drone.sjtu.edu.cn/contest/wp-content/uploads/2013/11/ROS_Gazebo_Quadrotor_simulator.pdf).
Use the ground truth topic (`/ground_truth/state`) and one of the topics that provide the altitude (`/altimeter` or `/ardrone/navdata`).

I also think that you could obtain it directly from the `gazebo/link_states` but it would be better if you use the previous approach.

**Comment by wajeehulhassanvii** [comment]
Thanks @eborghi10 , I'm very new to ROS. Actually somewhere in the code I found that they were using /drone/gt_pose which probably belongs to Parrot drone. Whereas this repository has ardrone, as you mentioned that we can use /ground_truth/state and /altimeter or /ardrone/navdata to get the pose of the drone, but I have no idea how I can make it work. 
I'd be thankful if you just give me some more detail so I can implement the topic or the code myself. Thanks

**Comment by wajeehulhassanvii** [comment]
I've created another issue for that and it's link is here. https://github.com/eborghi10/AR.Drone-ROS/issues/3
